
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jefe
 */
public class Ejemplo2 extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo2
     */
    public Ejemplo2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo = new javax.swing.JLabel();
        lblIngresar = new javax.swing.JLabel();
        txtOracion = new javax.swing.JTextField();
        BttnValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        LblTitulo.setText("toLowerCase");

        lblIngresar.setForeground(new java.awt.Color(51, 51, 255));
        lblIngresar.setText("INGRESE UNA PALABRA O ORACION");

        txtOracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOracionActionPerformed(evt);
            }
        });

        BttnValidar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BttnValidar.setForeground(new java.awt.Color(51, 255, 51));
        BttnValidar.setText("Validar");
        BttnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(LblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(txtOracion, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(BttnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LblTitulo)
                .addGap(38, 38, 38)
                .addComponent(lblIngresar)
                .addGap(31, 31, 31)
                .addComponent(txtOracion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(BttnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOracionActionPerformed

    private void BttnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnValidarActionPerformed

        String oracion=txtOracion.getText();
        this.cambiaroracion(oracion);        
    }//GEN-LAST:event_BttnValidarActionPerformed

    
    public void cambiaroracion (String oracion){
 if (oracion.isEmpty()) {
        JOptionPane.showMessageDialog(null, "La oración no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Sale del método si la validación no pasa
     }

    // Validar que la cadena no contenga números
     if (contieneNumeros(oracion)) {
        JOptionPane.showMessageDialog(null, "La oración no puede contener números", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Sale del método si la validación no pasa
     }

    // Convertir la oración a minúsculas
    String oracionEnMinusculas = oracion.toLowerCase();
    
    // Hacer lo que necesites con la oración en minúsculas
    // Por ejemplo, podrías mostrarla en un cuadro de diálogo
    JOptionPane.showMessageDialog(null, "" + oracionEnMinusculas);
}

private boolean contieneNumeros(String cadena) {
    // Verificar si la cadena contiene algún dígito
    for (char c : cadena.toCharArray()) {
        if (Character.isDigit(c)) {
            return true; // La cadena contiene al menos un dígito
        }
    }
    return false;  
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnValidar;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JTextField txtOracion;
    // End of variables declaration//GEN-END:variables
}
